the2:
	gcc -ansi -Wall -pedantic-errors the2.c main.c -o the
test1:
	gcc -ansi -Wall -pedantic-errors the2.c tests/1_print_storage1.c -o the
test2:
	gcc -ansi -Wall -pedantic-errors the2.c tests/2_print_storage2.c -o the
test3:
	gcc -ansi -Wall -pedantic-errors the2.c tests/3_insert1.c -o the
test4:
	gcc -ansi -Wall -pedantic-errors the2.c tests/4_insert2.c -o the
test5:
	gcc -ansi -Wall -pedantic-errors the2.c tests/5_insert_with_da_ext1.c -o the
test6:
	gcc -ansi -Wall -pedantic-errors the2.c tests/6_insert_with_da_ext2.c -o the
test7:
	gcc -ansi -Wall -pedantic-errors the2.c tests/7_insert_with_ia_ext1.c -o the
test8:
	gcc -ansi -Wall -pedantic-errors the2.c tests/8_insert_with_ia_ext2.c -o the
