the3:
	gcc -ansi -Wall -pedantic-errors the3.c main.c -o the
test1:
	gcc -ansi -Wall -pedantic-errors the3.c tests/1_create_student.c -o the
test2:
	gcc -ansi -Wall -pedantic-errors the3.c tests/2_create_course.c -o the
test3:
	gcc -ansi -Wall -pedantic-errors the3.c tests/3_new_request1.c -o the
test4:
	gcc -ansi -Wall -pedantic-errors the3.c tests/4_new_request2.c -o the
test5:
	gcc -ansi -Wall -pedantic-errors the3.c tests/5_new_request3.c -o the
test6:
	gcc -ansi -Wall -pedantic-errors the3.c tests/6_remaining_credits1.c -o the
test7:
	gcc -ansi -Wall -pedantic-errors the3.c tests/7_remaining_credits2.c -o the
test8:
	gcc -ansi -Wall -pedantic-errors the3.c tests/8_all_process1.c -o the
test9:
	gcc -ansi -Wall -pedantic-errors the3.c tests/9_all_process2.c -o the
test10:
	gcc -ansi -Wall -pedantic-errors the3.c tests/10_all_process3.c -o the